# Generated by Django 3.0.6 on 2020-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200528_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
